### ISSUE TITLE
Use Semantic Versioning?

### ISSUE THREAD

**Issue by chaziz94** [chazizsquarebracket/squarebracket#18]
Milestone 3 probably shouldn't be called "Milestone 3". It's a dumb thing referencing Microsoft's pre-alpha builds of the Windows operating system (as well as their other software if I remember correctly).

So, for retrocalling...
* Milestone 1 will be 0.1.0.
* Milestone 2 Preview will be 0.2.0
* Milestone 2 Refresh will be 0.2.5(?)

This would mean that the planned Milestone 3 should be 0.3.0.

**Comment by chaziz94** [comment]
Note that this could happen on Milestone 2 Refresh, though it's still planned to be released as, you've guessed it, Milestone 2 Refresh.

**Comment by chaziz94** [comment]
for MS1 maintained version 1 it should be 0.1.1. now it might be confusing because it's not based on final Milestone 1, it's based on a pre-release version of it.

though at that point i'd consider the released Milestone 1 to just be a pre-Milestone 2 version.

**Comment by forkiesassds** [comment]
I have no clue where this is going considering the current version is Alpha 3.

**Comment by chaziz94** [comment]
nope.
