### ISSUE TITLE
css won't compile/work (Win11 22000, XAMPP env)

### ISSUE THREAD

**Issue by haydenwalker980** [chazizsquarebracket/squarebracket#42]

**Comment by chaziz94** [comment]
can you give more description into what's happening?

**Comment by rollerozxa** [comment]
Which SCSS compiler did you try using? Have you added PHP to your PATH? Have you downloaded the required Composer dependencies?

**Comment by forkiesassds** [comment]
Are you sure you have the composer dependencies for pscss or have dart-sass or sassc compilers installed?

**Comment by chaziz94** [comment]
locked due to suspicious association with subrocks

**Comment by veselcraft** [comment]
> ![image](https://user-images.githubusercontent.com/45898787/125228762-5e9fa700-e2a3-11eb-8a69-87a123ac3e72.png)

i am sorry but

https://user-images.githubusercontent.com/22993408/125356873-7c3a4280-e36f-11eb-8c39-1adc402dad54.mp4

**Comment by forkiesassds** [comment]
Looks like a dev had paranoia from those guys. All just because of a forked repo...

**Comment by chaziz94** [comment]
that's not even paranoia you retard. the guy closed this issue most likely because he realized he didn't run the command in the proper directory.

**Comment by chaziz94** [comment]
![image](https://user-images.githubusercontent.com/45898787/125358109-80963980-e336-11eb-8778-bf20669f582e.png)

![image](https://user-images.githubusercontent.com/45898787/125358119-84c25700-e336-11eb-9faa-ec327e92e21e.png)
