### ISSUE TITLE
Thumbnails has the same size as videos on mobile.

### ISSUE THREAD

**Issue by chaziz94** [chazizsquarebracket/squarebracket#5]
<details><summary>
Resolved stuff can be toggled</summary>

Comparing Bootstrap 3 (which is on main branch) and the Bootstrap 5 branch. I noticed some stuff I don't really like.

# Inconsistencies
## Everything is slightly larger

BS5 | BS3
--- | --- 
![image](https://user-images.githubusercontent.com/45898787/117321305-04c1d180-ae5b-11eb-8b0b-07a717e91e7f.png) | ![image](https://user-images.githubusercontent.com/45898787/117321384-12775700-ae5b-11eb-9306-34c0bcf0e6ea.png)

## Profile cards aren't properly centered

BS5 | BS3
--- | --- 
![image](https://user-images.githubusercontent.com/45898787/117322606-266f8880-ae5c-11eb-9533-3d1c68a09918.png) | ![image](https://user-images.githubusercontent.com/45898787/117321566-3cc91480-ae5b-11eb-8e4f-d7c834da8203.png)

## Segoe UI looks off
BS5 | BS3
--- | --- 
![image](https://user-images.githubusercontent.com/45898787/117322136-bb25b680-ae5b-11eb-895c-3eee04b36f29.png) | ![image](https://user-images.githubusercontent.com/45898787/117322503-1061c800-ae5c-11eb-8972-dd3ce831eafe.png)

We shouldn't use Segoe UI mainly due to one reason. Nearly a decade ago, Microsoft made a massive fuck up by making some tweaks to the font on Windows 8.</details>

# Annoying stuff
For mobile users, the player will be the same size as the video thumbnails. This is a bad idea.
![image](https://user-images.githubusercontent.com/45898787/117321910-89145480-ae5b-11eb-82c3-f63c74ae73fb.png)

**Comment by forkiesassds** [comment]
> ## Everything is slightly larger
> BS5 	BS3
> ![image](https://user-images.githubusercontent.com/45898787/117321305-04c1d180-ae5b-11eb-8b0b-07a717e91e7f.png) 	![image](https://user-images.githubusercontent.com/45898787/117321384-12775700-ae5b-11eb-9306-34c0bcf0e6ea.png)
Can't fix, sorry.

> ## Profile cards aren't properly centered
> BS5 	BS3
> ![image](https://user-images.githubusercontent.com/45898787/117322606-266f8880-ae5c-11eb-9533-3d1c68a09918.png) 	![image](https://user-images.githubusercontent.com/45898787/117321566-3cc91480-ae5b-11eb-8e4f-d7c834da8203.png)
Fixed.

> ## Segoe UI looks off
> BS5 	BS3
> ![image](https://user-images.githubusercontent.com/45898787/117322136-bb25b680-ae5b-11eb-895c-3eee04b36f29.png) 	![image](https://user-images.githubusercontent.com/45898787/117322503-1061c800-ae5c-11eb-8972-dd3ce831eafe.png)
> 
> We shouldn't use Segoe UI mainly due to one reason. Nearly a decade ago, Microsoft made a massive fuck up by making some tweaks to the font on Windows 8.
It's not that big of a deal

> # Annoying stuff
> 
> For mobile users, the player will be the same size as the video thumbnails. This is a bad idea.
> ![image](https://user-images.githubusercontent.com/45898787/117321910-89145480-ae5b-11eb-82c3-f63c74ae73fb.png)
I either hardcode the size for the thumbnail or keep it like that.

**Comment by chaziz94** [comment]
> Can't fix, sorry.
pretty sure it's possible if you specifize the font size as being 14px instead of 1rem or whatever it's called 

> Segoe UI looks off
remember how intially i thought segoe ui was bad but ended up using it? that's because it looked good on BS3. they poorly executed it in BS4 and 5.

> I either hardcode the size for the thumbnail or keep it like that.
probably just hardcode it for now, we are in pre-alpha, we're fine with not good design.

**Comment by forkiesassds** [comment]
> pretty sure it's possible if you specifize the font size as being 14px instead of 1rem or whatever it's called

Uhhh, that would require changing a lot of variables and loads of math.

> remember how intially i thought segoe ui was bad but ended up using it? that's because it looked good on BS3. they poorly executed it in BS4 and 5.

Might be due to how the font sizes are.

> probably just hardcode it for now, we are in pre-alpha, we're fine with not good design.
Baaaaaad idea, it won't be responsive anymore!

**Comment by chaziz94** [comment]
about icon issues, can we make a seperate branch off the BS5 branch and try different solutions that won't have to do with SVGs?

roller told me that this wouldn't happen on webkit/blink-based browsers. so this isn't really my fault, nor bootstrap developers' fault, nor your fault, but this is mozilla's fault.

**Comment by chaziz94** [comment]
> Microsoft made a massive fuck up by making some tweaks to the font on Windows 8.

THEY'RE REPEATING THIS ALL OVER AGAIN FOR SUN VALLEY

![image](https://user-images.githubusercontent.com/45898787/117337885-eb755100-ae6b-11eb-9630-e57d2b37cf25.png)

3 SEGOE UI VERSIONS? why? just why? why the fuck can't you just stick with the longhorn/vista/7 segoe font instead of making inconsistency issues 2 FUCKING TIMES??!

ok the longhorn/vista/7 segoe and 8 segoe diffrences was a bit minor. BUT SUN VALLEY SEGOE IS GOING TO BE A LOT MORE DIFFERENT THAN THE OLDER VERSIONS.

GOOD JOB MICROSOFT

THIS IS WHY YOU ARE KNOWN FOR INCONSISTENCY

**Comment by chaziz94** [comment]
i feel like there's some unfinished business here.

**Comment by chaziz94** [comment]
well, the sizing issues doesnt need to be fixed, my eyes are used to it now.

but the "annoying stuff" section still isn't fixed.

**Comment by chaziz94** [comment]
still not fixed, reput in backburner.

**Comment by forkiesassds** [comment]
fixed in 7bdb64c
