### ISSUE TITLE
Timeout issue when trying to upload a video.

### ISSUE THREAD

**Issue by chaziz94** [chazizsquarebracket/squarebracket#6]
![image](https://user-images.githubusercontent.com/45898787/117324256-a0ecd800-ae5d-11eb-9fa9-2e996d2fad2d.png)

This is on production... and this is a similar issue to what happened on PokTube.

**Comment by forkiesassds** [comment]
requires uploading process to be reworked, probably using ajax and some async stuff or something like that.

**Comment by forkiesassds** [comment]
fixed, but it does not work on production, have to wait until that bug is fixed.

**Comment by chaziz94** [comment]
> 
> 
> fixed, but it does not work on production, have to wait until that bug is fixed.

try clearing our the cache lmao

**Comment by forkiesassds** [comment]
implemented windows support to roller's much better code. it surely will work on production.
